export const API_MANAGE_USER_START = 'API_MANAGE_USER_START'
export const API_MANAGE_USER_SUCCESS = 'API_MANAGE_USER_SUCCESS'
export const API_MANAGE_USER_FAILED = 'API_MANAGE_USER_FAILED'
export const API_FETCH_SUCCESS = 'API_FETCH_SUCCESS'